import dotenv from 'dotenv';

dotenv.config();

const {
  PORT, NODE_ENV,
  DEV_DATABASE_URL,
  TEST_DATABASE_URL,
  PROD_DATABASE_URL,
  SALT_ROUND, TOKEN_SECRET_KEY,
  TOKEN_EXPIRATION,
  REFRESH_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_EXPIRATION,
} = process.env;

export {
  PORT,
  NODE_ENV,
  DEV_DATABASE_URL,
  TEST_DATABASE_URL,
  PROD_DATABASE_URL,
  SALT_ROUND,
  TOKEN_SECRET_KEY,
  TOKEN_EXPIRATION,
  REFRESH_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_EXPIRATION,

};
